apiVersion: v1
kind: Service
metadata:
  labels:
    app: finance-web
  name: finance-web
  namespace: default
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 80
    name: web
  selector:
    app: finance-web
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: finance-web
  labels:
    app: finance-web
spec:
  template:
    metadata:
      labels:
        app: finance-web
    spec:
      containers:
        - name: finance-web
          image: gcr.io/alert-synapse-211723/finance-web:0.0.7
          ports:
            - containerPort: 80
